version: '3.7'
services:
    database:
        build: ./database
        environment:
            POSTGRES_DB: datacatdb
            POSTGRES_USER: datacatdbuser
            POSTGRES_PASSWORD: datacatdbpassword
        networks:
            - default
        volumes:
            - data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "datacatdbuser"]
            interval: 10s
            start_period: 30s
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - "8888:8888"
        networks: 
            - default
        depends_on: 
            - database
volumes: 
    data:
