version: '3.7'
services:
    database:
        build: ./database
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: datacatdb
            POSTGRES_USER: datacatdbuser
            POSTGRES_PASSWORD: datacatdbpassword
        networks:
            - default
        volumes:
            - data:/var/lib/postgresql/data
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - "8888:8888"
        networks: 
            - default
        depends_on: 
            - database
volumes: 
    data: